# Copyright 2026 - AI4I. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Turn Python objects into the Markdown the reference pages are made of.

Docstrings are written for Python readers (reST roles, double backticks); the
docs need Markdown. Everything here is pure formatting, so it is easy to test.
"""

from __future__ import annotations

import enum
import inspect
import json
import re
from typing import Any, Mapping

import yaml
from pydantic import BaseModel

GENERATED = (
    "<!-- Generated by docs/scripts/generate_reference.py from the code. "
    "Do not edit by hand. -->"
)


def clean(text: str | None) -> str:
    """A docstring as Markdown: reST roles and ``code`` become `code`."""
    if not text:
        return ""
    text = inspect.cleandoc(text)
    text = re.sub(
        r":(?:class|attr|func|data|meth|mod|obj):`~?([^`]+)`",
        lambda m: f"`{m.group(1).split('.')[-1]}`",
        text,
    )
    text = re.sub(r"``(.+?)``", r"`\1`", text, flags=re.S)
    return escape_html(text)


def escape_html(text: str) -> str:
    """Escape ``<`` outside code spans, so CommonMark never reads it as HTML."""
    parts = text.split("`")
    for index in range(0, len(parts), 2):
        parts[index] = parts[index].replace("<", "&lt;")
    return "`".join(parts)


def cell(text: str) -> str:
    """Text that fits in one Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def first_sentence(text: str | None) -> str:
    """The opening sentence of a docstring, as one line."""
    flat = " ".join(clean(text).split())
    match = re.match(r"(.+?[.!?])(\s|$)", flat)
    return match.group(1) if match else flat


def jsonable(value: Any) -> Any:
    """``value`` as plain data, so it can be dumped to JSON or YAML."""
    if isinstance(value, BaseModel):
        return value.model_dump(mode="json")
    if isinstance(value, enum.Enum):
        return value.value
    if isinstance(value, Mapping):
        return {str(key): jsonable(item) for key, item in value.items()}
    if isinstance(value, (tuple, list, set, frozenset)):
        return [jsonable(item) for item in value]
    return value


def code(value: Any) -> str:
    """A value as inline code, spelled the way YAML spells it."""
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, enum.Enum):
        value = value.value
    if isinstance(value, str):
        return f"`{value}`" if value else '`""`'
    dumped = json.dumps(jsonable(value), ensure_ascii=False)
    return f"`{dumped}`" if len(dumped) <= 60 else "_see the code_"


def yaml_block(data: Any, language: str = "yaml") -> str:
    """A fenced code block holding ``data`` as YAML."""
    body = yaml.safe_dump(
        jsonable(data), sort_keys=False, allow_unicode=True, width=88
    ).rstrip()
    return f"```{language}\n{body}\n```"


def page(front: Mapping[str, Any], body: str) -> str:
    """A docs page: front matter, the generated-file notice, then ``body``."""
    matter = "\n".join(
        f"{key}: {json.dumps(value, ensure_ascii=False)}"
        for key, value in front.items()
    )
    return f"---\n{matter}\n---\n\n{GENERATED}\n\n{body.strip()}\n"


def table(headers: list[str], rows: list[list[str]]) -> str:
    """A Markdown table. Returns an empty string when there are no rows."""
    if not rows:
        return ""
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    lines += ["| " + " | ".join(cell(column) for column in row) + " |" for row in rows]
    return "\n".join(lines)


def admonition(kind: str, title: str, body: str) -> str:
    """A Docusaurus admonition (``tip``, ``note``, ``caution``…)."""
    return f":::{kind}[{title}]\n\n{body.strip()}\n\n:::"
