repos:
- hooks:
  - id: commitizen
    stages: [commit-msg]
    additional_dependencies: [cz-conventional-gitmoji]
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.7.0
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version. Optional: Ruff will find and use the project's Ruff version Ruff otherwise.
  rev: v0.5.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format

-   repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
