# Copyright 2026 - AI4I. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Composable h4rm3l prompt decorators and compiler."""

from .base import (
    DecorationResult,
    LLMPromptDecorator,
    PromptDecorator,
)
from .compiler import (
    LLM_ASSISTED_DECORATOR_NAMES,
    compile_program,
    is_llm_assisted_decorator_name,
    program_uses_llm_assisted_decorators,
)
from .llm import (
    PAPDecorator,
    PersonaDecorator,
    PersuasiveDecorator,
    ResearcherDecorator,
    SynonymDecorator,
    TransformFxDecorator,
    TranslateDecorator,
    VillainDecorator,
    VisualObfuscationDecorator,
)
from .static import (
    AIMDecorator,
    AffirmativePrefixInjectionDecorator,
    AnswerStyleDecorator,
    Base64Decorator,
    ChainofThoughtDecorator,
    CharCorrupt,
    CharDropout,
    CipherDecorator,
    ColorMixInDecorator,
    DANDecorator,
    DialogStyleDecorator,
    DistractorDecorator,
    FewShotDecorator,
    HexStringMixInDecorator,
    IdentityDecorator,
    JekyllHydeDialogStyleDecorator,
    LIVEGPTDecorator,
    MilitaryWordsMixInDecorator,
    PayloadSplittingDecorator,
    QuestionIdentificationDecorator,
    RefusalSuppressionDecorator,
    ReverseDecorator,
    RoleplayingDecorator,
    STANDecorator,
    StyleInjectionJSONDecorator,
    StyleInjectionShortDecorator,
    TemplateDecorator,
    TranslateBackDecorator,
    UTADecorator,
    WikipediaDecorator,
    WordMixInDecorator,
)

__all__ = [
    "AIMDecorator",
    "AffirmativePrefixInjectionDecorator",
    "AnswerStyleDecorator",
    "Base64Decorator",
    "ChainofThoughtDecorator",
    "CharCorrupt",
    "CharDropout",
    "CipherDecorator",
    "ColorMixInDecorator",
    "DANDecorator",
    "DecorationResult",
    "DialogStyleDecorator",
    "DistractorDecorator",
    "FewShotDecorator",
    "HexStringMixInDecorator",
    "IdentityDecorator",
    "JekyllHydeDialogStyleDecorator",
    "LIVEGPTDecorator",
    "LLM_ASSISTED_DECORATOR_NAMES",
    "LLMPromptDecorator",
    "MilitaryWordsMixInDecorator",
    "PAPDecorator",
    "PayloadSplittingDecorator",
    "PersonaDecorator",
    "PersuasiveDecorator",
    "PromptDecorator",
    "QuestionIdentificationDecorator",
    "RefusalSuppressionDecorator",
    "ResearcherDecorator",
    "ReverseDecorator",
    "RoleplayingDecorator",
    "STANDecorator",
    "StyleInjectionJSONDecorator",
    "StyleInjectionShortDecorator",
    "SynonymDecorator",
    "TemplateDecorator",
    "TransformFxDecorator",
    "TranslateBackDecorator",
    "TranslateDecorator",
    "UTADecorator",
    "VillainDecorator",
    "VisualObfuscationDecorator",
    "WikipediaDecorator",
    "WordMixInDecorator",
    "compile_program",
    "is_llm_assisted_decorator_name",
    "program_uses_llm_assisted_decorators",
]
