#!/usr/bin/env bash
# Copyright 2026 - AI4I. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Build the HackAgent web UI bundle that `hackagent web` serves.
#
# Produces a static export of the hackagent-webapp single-page app into
# hackagent/server/webui/static/, where the package finds it at runtime and
# PyInstaller picks it up for release binaries.
#
# The webapp checkout is never modified: the sources are copied to a scratch
# directory and the export is configured there. That matters because the webapp
# is built for a Node deployment — it ships server route handlers for its API
# proxy and its runtime config, and `output: 'export'` rejects those. The CLI
# serves both of those itself (hackagent/server/webui/_proxy.py and
# /config.json), so the routes are simply left out of this build.
#
# Usage:
#   scripts/build_webui.sh [WEBAPP_DIR]
#
# The webapp checkout is resolved from, in order: the first argument,
# $HACKAGENT_WEBAPP_DIR, ../hackagent-webapp, or a shallow clone of
# $HACKAGENT_WEBAPP_REPO at $HACKAGENT_WEBAPP_REF.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${REPO_ROOT}/hackagent/server/webui/static"

WEBAPP_REPO="${HACKAGENT_WEBAPP_REPO:-https://github.com/AISecurityLab/hackagent-webapp.git}"
WEBAPP_REF="${HACKAGENT_WEBAPP_REF:-main}"

# Server-only sources that a static export cannot contain. The CLI answers both
# of these paths from Python instead.
EXCLUDED_ROUTES=(
  "src/app/api"
  "src/app/config.json"
)

log()  { printf '\033[36m▸\033[0m %s\n' "$*"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

command -v node >/dev/null 2>&1 || die "node is required (18+); install Node.js first."
command -v npm  >/dev/null 2>&1 || die "npm is required; install Node.js first."

# ── Resolve the webapp sources ───────────────────────────────────────────────
SCRATCH="$(mktemp -d)"
trap 'rm -rf "${SCRATCH}"' EXIT

SOURCE="${1:-${HACKAGENT_WEBAPP_DIR:-}}"
if [[ -z "${SOURCE}" && -d "${REPO_ROOT}/../hackagent-webapp" ]]; then
  SOURCE="${REPO_ROOT}/../hackagent-webapp"
fi
if [[ -z "${SOURCE}" ]]; then
  log "No webapp checkout found; cloning ${WEBAPP_REPO} @ ${WEBAPP_REF}"
  git clone --depth 1 --branch "${WEBAPP_REF}" "${WEBAPP_REPO}" "${SCRATCH}/webapp-src"
  SOURCE="${SCRATCH}/webapp-src"
fi
[[ -f "${SOURCE}/package.json" ]] || die "Not a webapp checkout: ${SOURCE}"
SOURCE="$(cd "${SOURCE}" && pwd)"
log "Webapp sources: ${SOURCE}"

# ── Copy sources into scratch, leaving the checkout untouched ────────────────
BUILD="${SCRATCH}/build"
log "Copying sources to a scratch build directory"
mkdir -p "${BUILD}"
tar -C "${SOURCE}" \
    --exclude=node_modules --exclude=.next --exclude=.git --exclude=out \
    -cf - . | tar -C "${BUILD}" -xf -

for route in "${EXCLUDED_ROUTES[@]}"; do
  if [[ -e "${BUILD}/${route}" ]]; then
    log "Excluding server route: ${route}"
    rm -rf "${BUILD:?}/${route}"
  fi
done

# ── Configure the export ─────────────────────────────────────────────────────
# Written rather than patched so the result does not depend on the shape of the
# webapp's own next.config.js, which changes independently of this script.
cat > "${BUILD}/next.config.js" <<'JS'
/** @type {import('next').NextConfig} */
// Generated by hackagent's scripts/build_webui.sh — static export for the CLI.
const nextConfig = {
  output: 'export',
  reactStrictMode: true,
  // Required by `output: 'export'`: there is no server to optimise images.
  images: { unoptimized: true },
  // The CLI serves clean URLs (/agents -> agents.html), so keep flat filenames.
  trailingSlash: false,
  // Type and lint errors are the webapp CI's job; a packaging build should not
  // fail on them and block a release.
  typescript: { ignoreBuildErrors: true },
  eslint: { ignoreDuringBuilds: true },
  webpack: (config) => {
    config.externals.push('pino-pretty', 'lokijs', 'encoding');
    return config;
  },
};

module.exports = nextConfig;
JS

# ── Install and build ────────────────────────────────────────────────────────
if [[ -d "${SOURCE}/node_modules" ]]; then
  log "Reusing node_modules from the checkout"
  ln -s "${SOURCE}/node_modules" "${BUILD}/node_modules"
else
  log "Installing dependencies (npm ci)"
  (cd "${BUILD}" && npm ci --ignore-scripts)
fi

log "Building the static export"
# NEXT_PUBLIC_* values are inlined at build time. The bundle must stay generic —
# every deployment-specific value is delivered at runtime via /config.json — so
# only the auth-disabled default is baked in.
(cd "${BUILD}" && NEXT_PUBLIC_DISABLE_AUTH=true NEXT_TELEMETRY_DISABLED=1 npm run build)

[[ -f "${BUILD}/out/index.html" ]] || die "Export produced no out/index.html"

# ── Install the bundle ───────────────────────────────────────────────────────
log "Installing bundle into ${DEST}"
rm -rf "${DEST}"
mkdir -p "${DEST}"
tar -C "${BUILD}/out" -cf - . | tar -C "${DEST}" -xf -

WEBAPP_VERSION="$(node -p "require('${BUILD}/package.json').version" 2>/dev/null || echo unknown)"
printf '%s\n' "${WEBAPP_VERSION}" > "${DEST}/VERSION"

SIZE="$(du -sh "${DEST}" | cut -f1)"
printf '\033[32m✓\033[0m Web UI bundle ready: %s (webapp %s, %s)\n' "${DEST}" "${WEBAPP_VERSION}" "${SIZE}"
printf '  Run it with: \033[1mhackagent web\033[0m\n'
