import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

function apiPackage(label: string, dir: string) {
  return {
    type: 'category' as const,
    label,
    items: [{type: 'autogenerated' as const, dirName: `hackagent/${dir}`}],
  };
}

// One sidebar per navbar tab: Guides, Reference, SDK and API.
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      className: 'sidebar-icon sidebar-icon-rocket',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/first-campaign',
        'getting-started/example-run',
        'getting-started/dashboard',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      className: 'sidebar-icon sidebar-icon-book',
      link: {type: 'doc', id: 'concepts/index'},
      items: [
        'concepts/how-a-run-works',
        'concepts/attacks-and-roles',
        'concepts/judges',
        'concepts/code-map',
      ],
    },
    {
      type: 'category',
      label: 'AI Risks',
      className: 'sidebar-icon sidebar-icon-shield-alert',
      link: {type: 'doc', id: 'risks/index'},
      items: [
        {
          type: 'category',
          label: 'Vulnerabilities',
          link: {type: 'doc', id: 'risks/vulnerabilities'},
          items: [
            'risks/vulnerabilities/jailbreak',
            'risks/vulnerabilities/prompt-injection',
            'risks/vulnerabilities/system-prompt-leakage',
            'risks/vulnerabilities/input-manipulation-attack',
            'risks/vulnerabilities/model-evasion',
            'risks/vulnerabilities/craft-adversarial-data',
            'risks/vulnerabilities/sensitive-information-disclosure',
            'risks/vulnerabilities/misinformation',
            'risks/vulnerabilities/excessive-agency',
            'risks/vulnerabilities/malicious-tool-invocation',
            'risks/vulnerabilities/credential-exposure',
            'risks/vulnerabilities/public-facing-application-exploitation',
            'risks/vulnerabilities/vector-embedding-weaknesses-exploit',
          ],
        },
        'risks/custom-vulnerabilities',
        {
          type: 'category',
          label: 'Evaluation Campaigns',
          link: {type: 'doc', id: 'risks/evaluation-campaigns'},
          items: [
            'risks/evaluation-campaigns/quick-scan',
            'risks/evaluation-campaigns/comprehensive-audit',
            'risks/evaluation-campaigns/targeted-assessment',
            'risks/evaluation-campaigns/custom-campaigns',
          ],
        },
        {
          type: 'doc',
          id: 'risks/indirect-prompt-injection',
          label: 'Indirect Prompt Injection',
        },
      ],
    },
    {
      type: 'category',
      label: 'Security & Ethics',
      className: 'sidebar-icon sidebar-icon-lock',
      items: ['security/responsible-disclosure', 'security/ethical-guidelines'],
    },
  ],
  referenceSidebar: [
    {type: 'doc', id: 'reference/index', label: 'Overview'},
    'reference/campaign',
    'reference/dataset',
    'reference/target',
    'reference/guardrails',
    'reference/evaluation',
    'reference/execution',
    {
      type: 'category',
      label: 'Attack catalog',
      link: {type: 'doc', id: 'reference/attacks/index'},
      items: [{type: 'autogenerated', dirName: 'reference/attacks'}],
    },
    'reference/cli',
  ],
  // Generated from the source by docs/scripts/generate_docs.py, so a module
  // that comes or goes cannot leave a stale entry behind.
  sdkSidebar: [
    {type: 'doc', id: 'api-index', label: 'Overview'},
    {type: 'doc', id: 'hackagent/client', label: 'Client'},
    apiPackage('Interfaces', 'interfaces'),
    apiPackage('Core', 'core'),
    apiPackage('Models', 'models'),
    apiPackage('Evaluation', 'evaluation'),
    apiPackage('Tracking', 'tracking'),
    apiPackage('Orchestrator', 'orchestrator'),
    apiPackage('Attacks', 'attacks'),
    apiPackage('Datasets', 'datasets'),
    apiPackage('Catalog', 'catalog'),
    apiPackage('Storage', 'storage'),
  ],
  apiSidebar: ['api/index'],
};

export default sidebars;
