import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
/**
 * Creating a sidebar allows you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      className: 'sidebar-icon sidebar-icon-rocket',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/first-campaign',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      className: 'sidebar-icon sidebar-icon-book',
      items: [
        'concepts/how-a-run-works',
        'concepts/attacks-and-roles',
        'concepts/judges',
        'concepts/code-map',
      ],
    },
    {
      type: 'category',
      label: 'AI Risks',
      className: 'sidebar-icon sidebar-icon-shield-alert',
      link: {
        type: 'doc',
        id: 'risks/index',
      },
      items: [
        {
          type: 'category',
          label: 'Vulnerabilities',
          link: {
            type: 'doc',
            id: 'risks/vulnerabilities',
          },
          items: [
            'risks/vulnerabilities/jailbreak',
            'risks/vulnerabilities/prompt-injection',
            'risks/vulnerabilities/system-prompt-leakage',
            'risks/vulnerabilities/input-manipulation-attack',
            'risks/vulnerabilities/model-evasion',
            'risks/vulnerabilities/craft-adversarial-data',
            'risks/vulnerabilities/sensitive-information-disclosure',
            'risks/vulnerabilities/misinformation',
            'risks/vulnerabilities/excessive-agency',
            'risks/vulnerabilities/malicious-tool-invocation',
            'risks/vulnerabilities/credential-exposure',
            'risks/vulnerabilities/public-facing-application-exploitation',
            'risks/vulnerabilities/vector-embedding-weaknesses-exploit',
          ],
        },
        'risks/custom-vulnerabilities',
        {
          type: 'category',
          label: 'Evaluation Campaigns',
          link: {
            type: 'doc',
            id: 'risks/evaluation-campaigns',
          },
          items: [
            'risks/evaluation-campaigns/quick-scan',
            'risks/evaluation-campaigns/comprehensive-audit',
            'risks/evaluation-campaigns/targeted-assessment',
            'risks/evaluation-campaigns/custom-campaigns',
          ],
        },
        {
          type: 'doc',
          id: 'risks/indirect-prompt-injection',
          label: 'Indirect Prompt Injection',
        },
      ],
    },
    {
      type: 'category',
      label: 'Campaign Reference',
      className: 'sidebar-icon sidebar-icon-sword',
      link: {
        type: 'doc',
        id: 'reference/index',
      },
      items: [
        'reference/campaign',
        'reference/dataset',
        'reference/target',
        'reference/guardrails',
        'reference/evaluation',
        'reference/execution',
        {
          type: 'category',
          label: 'Attack catalog',
          link: {
            type: 'doc',
            id: 'reference/attacks/index',
          },
          items: [{type: 'autogenerated', dirName: 'reference/attacks'}],
        },
        'reference/cli',
      ],
    },
    {
      type: 'category',
      label: 'SDK Reference',
      className: 'sidebar-icon sidebar-icon-code',
      link: {
        type: 'doc',
        id: 'api-index',
      },
      // Generated from the source by docs/scripts/generate_docs.py, so this
      // list is autogenerated too: a module that comes or goes cannot leave a
      // stale entry behind.
      items: [{type: 'autogenerated', dirName: 'hackagent'}],
    },
    {
      type: 'category',
      label: 'Security & Ethics',
      className: 'sidebar-icon sidebar-icon-lock',
      items: [
        'security/responsible-disclosure',
        'security/ethical-guidelines',
      ],
    },
  ]
};

export default sidebars;
