import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One SDK sidebar category per package. The items are autogenerated from the
// generated reference under docs/hackagent/<dir>, so every module page is
// listed without keeping a hand-written copy of the package tree. `overview`
// is the hand-written page that opens when the category label is clicked.
function apiPackage(label: string, dir: string, overview?: string) {
  return {
    type: 'category' as const,
    label,
    ...(overview ? {link: {type: 'doc' as const, id: overview}} : {}),
    items: [{type: 'autogenerated' as const, dirName: `hackagent/${dir}`}],
  };
}

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      className: 'sidebar-icon sidebar-icon-rocket',
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/quick-security-scan',
        'getting-started/attack-tutorial',
        'getting-started/datasets-tutorial',
      ],
    },
    {
      type: 'category',
      label: 'AI Risks',
      className: 'sidebar-icon sidebar-icon-shield-alert',
      link: {
        type: 'doc',
        id: 'risks/index',
      },
      items: [
        {
          type: 'category',
          label: 'Vulnerabilities',
          link: {
            type: 'doc',
            id: 'risks/vulnerabilities',
          },
          items: [
            'risks/vulnerabilities/jailbreak',
            'risks/vulnerabilities/prompt-injection',
            'risks/vulnerabilities/system-prompt-leakage',
            'risks/vulnerabilities/input-manipulation-attack',
            'risks/vulnerabilities/model-evasion',
            'risks/vulnerabilities/craft-adversarial-data',
            'risks/vulnerabilities/sensitive-information-disclosure',
            'risks/vulnerabilities/misinformation',
            'risks/vulnerabilities/excessive-agency',
            'risks/vulnerabilities/malicious-tool-invocation',
            'risks/vulnerabilities/credential-exposure',
            'risks/vulnerabilities/public-facing-application-exploitation',
            'risks/vulnerabilities/vector-embedding-weaknesses-exploit',
          ],
        },
        'risks/custom-vulnerabilities',
        {
          type: 'category',
          label: 'Evaluation Campaigns',
          link: {
            type: 'doc',
            id: 'risks/evaluation-campaigns',
          },
          items: [
            'risks/evaluation-campaigns/quick-scan',
            'risks/evaluation-campaigns/comprehensive-audit',
            'risks/evaluation-campaigns/targeted-assessment',
            'risks/evaluation-campaigns/custom-campaigns',
          ],
        },
        {
          type: 'doc',
          id: 'risks/indirect-prompt-injection',
          label: 'Indirect Prompt Injection',
        },
      ],
    },
    {
      type: 'category',
      label: 'Attacks',
      className: 'sidebar-icon sidebar-icon-sword',
      link: {
        type: 'doc',
        id: 'attacks/index',
      },
      items: [
        'attacks/taxonomy',
        'attacks/shared-args',
        {
          type: 'category',
          label: 'Jailbreak',
          items: [
            {
              type: 'category',
              label: 'Static',
              collapsed: false,
              items: [
                'attacks/baseline',
                'attacks/static-template',
                'attacks/flipattack',
                'attacks/cipherchat',
                'attacks/h4rm3l',
                'attacks/mml',
                'attacks/fc',
                'attacks/tfc',
              ],
            },
            {
              type: 'category',
              label: 'Adaptive',
              collapsed: false,
              items: [
                'attacks/pair',
                'attacks/tap',
                'attacks/pap',
                'attacks/bon',
                'attacks/advprefix',
                'attacks/autodan_turbo',
              ],
            },
            {
              type: 'category',
              label: 'Multi-turn',
              collapsed: false,
              items: [
                'attacks/crescendo',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Indirect Injection',
          items: [
            'attacks/rag',
            'attacks/tool_output_ipi',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Datasets',
      className: 'sidebar-icon sidebar-icon-database',
      link: {
        type: 'doc',
        id: 'datasets/index',
      },
      items: [
        'datasets/selecting-intent-categories',
        'datasets/presets',
        'datasets/huggingface',
        'datasets/url-json',
        'datasets/file',
        'datasets/custom-providers',
        'datasets/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      className: 'sidebar-icon sidebar-icon-cpu',
      link: {
        type: 'doc',
        id: 'agents/index',
      },
      items: [
        {
          type: 'doc',
          id: 'agents/ollama',
          label: 'Ollama',
        },
        {
          type: 'doc',
          id: 'agents/openai-sdk',
          label: 'OpenAI SDK',
        },
        {
          type: 'doc',
          id: 'agents/google-adk',
          label: 'Google ADK',
        },
        {
          type: 'doc',
          id: 'agents/claude-code',
          label: 'Claude Code',
        },
        {
          type: 'doc',
          id: 'agents/codex',
          label: 'Codex',
        },
        {
          type: 'doc',
          id: 'agents/hermes',
          label: 'Hermes Agent',
        },
        {
          type: 'doc',
          id: 'agents/guardrails',
          label: 'Guardrails',
        },
      ],
    },
    {
      type: 'category',
      label: 'Security & Ethics',
      className: 'sidebar-icon sidebar-icon-lock',
      items: [
        'security/responsible-disclosure',
        'security/ethical-guidelines',
      ],
    },
  ],
  sdkSidebar: [
    {
      type: 'doc',
      id: 'api-index',
      label: 'Overview',
    },
    'sdk/python-quickstart',
    {
      type: 'doc',
      id: 'architecture/system-overview',
      label: 'Architecture',
    },
    {
      type: 'category',
      label: 'Client',
      link: {type: 'doc', id: 'client/index'},
      items: ['hackagent/client'],
    },
    apiPackage('Interfaces', 'interfaces'),
    apiPackage('Core', 'core'),
    apiPackage('Models', 'models'),
    apiPackage('Evaluation', 'evaluation', 'evaluation/index'),
    apiPackage('Tracking', 'tracking', 'tracking/index'),
    apiPackage('Orchestrator', 'orchestrator', 'orchestrator/index'),
    apiPackage('Attacks', 'attacks', 'attacks/seam'),
    apiPackage('Datasets', 'datasets'),
    apiPackage('Catalog', 'catalog'),
    apiPackage('Storage', 'storage'),
  ],
  cliSidebar: [
    'cli/overview',
    'cli/initialization',
    'cli/config',
    'cli/agent',
    'cli/eval',
    'cli/scan',
    'cli/results',
    'cli/datasets',
    'cli/web',
  ],
  apiSidebar: ['api/index'],
};

export default sidebars;
